name: .NET Core Desktop

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: windows-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    # Install the .NET Core workload
    - name: Install .NET Core
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x

    - name: Restore dependencies
      working-directory: Windows
      run: dotnet restore

    - name: Build WPF application
      working-directory: Windows
      run: dotnet publish JeepDiag.WPF -c Release -r win-x64 --self-contained false -o output

    - name: Create ZIP package
      working-directory: Windows
      run: Compress-Archive -Path output/* -DestinationPath release.zip

    - name: Upload build artifact
      uses: actions/upload-artifact@v4
      with:
        name: windows-wpf-build
        path: Windows/release.zip
